#!/bin/bash

################################################################################
# File: runScalingTests.bash
#
# Description: This bash shell script submits one PBS job for each subdirectory
# in the top-level directory specified by test_set.  The subdirectories are
# generated by the prepareScalingTests.bash script, and they represent the
# different combinations of number of nodes, threads, and clusters to for which
# performance tests are to be run.  A wall time given by wall_time must be
# provided to specify the maximum run time of each PBS job.  The numbers of
# nodes, numbers of threads, and numbers of clusters to be discovered are
# specified with num_nodes, num_threads, and num_clusters, array arguments
# respectively.
#
# Arguments:
#   test_set - the name of the directory where all of the performance tests
#     are defined; it should be in the same directory as this script.
#
#   wall_time - the maximum wall clock time of all of the batch jobs that
#     execute the performance tests; it should be in a format supported by
#     the PBS qsub command.
#
#   num_nodes - an array of numbers of nodes to be tested with; the array must
#     be specified in double digits.
#     Example: "01 02 03 04" for testing with 1, 2, 3, and 4 nodes. 
#
#   num_threads - an array of numbers of threads to be tested; the array must be
#     specified in double digits.
#     Example: "01 02 04 08 16" for testing with 1, 2, 4, 8, and 16 nodes. 
#
#   num_clusters - an array of numbers of clusters to be tested; the array must
#     be specified in double digits.
#     Example: "01000 02000 04000 08000 15000" for testing with 1000, 2000,
#     4000, 8000, and 15000 nodes. 
#
# Author: James R. McCombs, Pervasive Technology Institute, Indiana University 
################################################################################

prog="runScalingTests.bash"
USAGE="USAGE: $prog test_set wall_time num_nodes num_threads num_clusters"

if [[ $# -ne 5 ]]; then
  echo "$USAGE"
  exit 1
fi

TEST_SET=$1
WALL_TIME=$2
NUM_NODES=$3
NUM_THREADS=$4
NUM_CLUSTERS=$5

cd $TEST_SET

if [[ $? -ne 0 ]]; then
   echo "ERROR: No test set directory $TEST_SET" 1>&2
   exit 1
fi

for n in $NUM_NODES; do
   for t in $NUM_THREADS; do
      for c in $NUM_CLUSTERS; do
         test_id=${n}_${t}_${c}

         cd $test_id

         if [[ $? -ne 0 ]]; then
            echo "WARNING: No test id directory $test_id" 1>&2
            continue
         fi

         qsub -l nodes=$((10#$n)):ppn=16,walltime=${WALL_TIME} -N ${TEST_SET}_${n}_${t}_${c} ../../scaleTestH2O.bash

         cd ..

      done   
   done
done

exit 0
